import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import Link from "next/link";
import { Sidebar } from "@/components/Sidebar";

const fontInter = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="initial-scale=1, width=device-width" />
      </head>
      <body className={`${fontInter.variable}`}>
        <Providers>
          <main className="main">
            <aside className="sidebar">SIDEBAR</aside>
            <section className="content">{children}</section>
          </main>
        </Providers>
      </body>
    </html>
  );
}
